train:
  model: "sovits"
  seed: 1234
  epochs: 10000
  learning_rate: 2e-4
  betas: [0.8, 0.99]
  lr_decay: 0.999875
  eps: 1e-9
  batch_size: 8
  accum_step: 4
  c_stft: 9
  c_mel: 45.
  c_kl: 1.
  port: 8001
  pretrain: "./model.pth"
  freeze_d_steps: 2000
#############################
data: 
  training_files: "files/train_lj.txt"
  validation_files: "files/val_lj.txt"
  segment_size: 12000  
  max_wav_value: 32768.0
  sampling_rate: 24000
  filter_length: 1024
  hop_length: 480
  win_length: 1024
  mel_channels: 100
  mel_fmin: 50.0
  mel_fmax: 12000.0
#############################
vits2:
  ppg_dim: 512
  vec_dim: 256
  spk_dim: 256
  gin_channels: 256
  inter_channels: 192
  hidden_channels: 192
  filter_channels: 640
  spec_channels: 513
  n_vocab: 100
  n_speakers: 1
  n_heads: 2
  n_layers: 6
  kernel_size: 3
  p_dropout: 0.1
  resblock: 1
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5],[1,3,5],[1,3,5]]
  upsample_rates: [8,8,2,2]
  upsample_initial_channel: 512
  upsample_kernel_sizes: [16,16,4,4]
  use_sdp: false
  
  
  use_spk_conditioned_encoder: True
  use_transformer_flows: True
  transformer_flow_type: "pre_conv"
  segment_size: 12000
  
#############################
gen:
  #spk_dim: 256
  upsample_input: 192
  upsample_rates: [6,5,2,2,2,2]
  upsample_kernel_sizes: [18,15,4,4,4,4]
#   upsample_rates: [11,5,5] # Multiplicacao desses numeros = hop size
#   upsample_kernel_sizes: [15,14,14]
  upsample_initial_channel: 480
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
#############################
mpd:
  periods: [2,3,5,7,11]
  kernel_size: 5
  stride: 3
  use_spectral_norm: False
  lReLU_slope: 0.2
#############################
mrd:
  resolutions: "[(1024, 120, 600), (2048, 240, 1200), (4096, 480, 2400), (512, 50, 240)]" # (filter_length, hop_length, win_length)
  use_spectral_norm: False
  lReLU_slope: 0.2
#############################
log:
  info_interval: 100
  eval_interval: 1
  save_interval: 5
  num_audio: 1
  pth_dir: 'chkpt'
  log_dir: 'logs'
  keep_ckpts: 3
#############################
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1